TopLearn/TopLearn.Web/Areas/Administrator/Pages/AccountManagement/Accounts/Index.cshtml.cs
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TopLearn.Web.Areas.Administrator.Pages.AccountManagement.Accounts
{
    public class IndexModel : PageModel
    {

        #region constructor injection

        private readonly IAccountApplication _accountApplication;
        private readonly IRoleApplication _roleApplication;

        public IndexModel(IAccountApplication accountApplication, IRoleApplication roleApplication)
        {
            _accountApplication = accountApplication;
            _roleApplication = roleApplication;
        }

        #endregion

        public List<AccountViewModel> Accounts { get; set; }
        public AccountSearchModel SearchModel { get; set; }

        public void OnGet(AccountSearchModel searchModel)
        {
            Accounts = _accountApplication.GetList(searchModel);
        }


        public async Task<IActionResult> OnGetCreate()
        {
            return Partial("Create", new CreateAccountCommand()
            {
                Roles = await _roleApplication.GetList()
            });
        }

        public async Task<IActionResult> OnPostCreate(CreateAccountCommand command, List<int> selectedRoles)
        {
            var result = await _accountApplication.Create(command, selectedRoles);


            return new JsonResult(result);
        }

        public async Task<IActionResult> OnGetActiveAccount(long id)
        {
            await _accountApplication.ActiveAccount(id);
            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnGetDeActiveAccount(long id)
        {
            await _accountApplication.DeActiveAccount(id);
            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnGetEdit(long id)
        {
            var model = await _accountApplication.GetDetails(id);
            model.Roles = await _roleApplication.GetList();
            return Partial("Edit", model);
        }

        public async Task<IActionResult> OnPostEdit(EditAccountCommand command, List<int> selectedRoles)
        {
            var result = await _accountApplication.Edit(command, selectedRoles);


            return new JsonResult(result);
        }
    }
}

TopLearn/TopLearn.Web/Areas/Administrator/Pages/AccountManagement/Roles/Index.cshtml.cs
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TopLearn.Web.Areas.Administrator.Pages.AccountManagement.Roles
{
    public class IndexModel : PageModel
    {
        #region constructor injection

        private readonly IRoleApplication _roleApplication;
        public IndexModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        #endregion

        public List<RoleViewModel> Roles { get; set; }

        public async Task OnGet()
        {
            Roles = await _roleApplication.GetList();
        }
    }
}

TopLearn/TopLearn.Web/Controllers/AccountController.cs
using _0.Framework.Application;
using _0.Framework.Application.Email;
using AccountManagement.Application.Contracts.Account;
using Microsoft.AspNetCore.Mvc;

namespace TopLearn.Web.Controllers
{
    public class AccountController : BaseController
    {
        #region constructor injection

        private readonly IAccountApplication _accountApplication;
        private readonly IViewRenderService _viewRenderService;
        public AccountController(IAccountApplication accountApplication, IViewRenderService viewRenderService)
        {
            _accountApplication = accountApplication;
            _viewRenderService = viewRenderService;
        }

        #endregion

        #region Register

        [Route("Register")]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost("Register")]
        public async Task<IActionResult> Register(AccountRegisterCommand command)
        {
            if (!ModelState.IsValid)
            {
                return View(command);
            }

            var result = await _accountApplication.RegisterAccount(command);

            if (result.Item1.Status == OperationResultStatus.Success)
            {

                #region Send Active Email

                var emailBody = _viewRenderService.RenderToStringAsync("_ActivateAccountEmail", result.Item2);
                SendEmail.Send(result.Item2.Email, "فعالسازی حساب", emailBody);

                #endregion

                SuccessAlert(result.Item1.Message);
                return View("SuccessRegister", result.Item2);
            }

            ErrorAlert(result.Item1.Message);
            return View(command);
        }

        #endregion

        #region Login

        [Route("Login")]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost("Login")]
        public async Task<IActionResult> Login(LoginAccountCommand command)
        {
            if (!ModelState.IsValid)
            {
                return View(command);
            }

            var result = await _accountApplication.LoginAccount(command);

            if (result.Status == OperationResultStatus.Success)
            {
                SuccessAlert(result.Message);
                return Redirect("/UserPanel");
            }

            ErrorAlert(result.Message);
            return View(command);
        }

        #endregion

        #region Active Account

        [Route("ActiveAccount")]
        public async Task<IActionResult> ActiveAccount(string activeCode)
        {
            var result = await _accountApplication.ActiveAccount(activeCode);

            switch (result.Status)
            {
                case OperationResultStatus.Error:
                    ErrorAlert(result.Message);
                    break;
                case OperationResultStatus.Success:
                    SuccessAlert(result.Message);
                    return RedirectToAction("Login", "Account");
                case OperationResultStatus.NotFound:
                    ErrorAlert(result.Message);
                    break;
                default:
                    return NotFound();
            }

            return Redirect("/");
        }

        #endregion

        #region Logout

        [Route("Logout")]
        public async Task<IActionResult> Logout()
        {
            var result = await _accountApplication.LogoutAccount();
            SuccessAlert(result.Message);
            return Redirect("/");
        }

        #endregion

        #region Forgot Password

        [Route("ForgotPassword")]
        public IActionResult ForgotPassword()
        {
            return View();
        }

        [HttpPost("ForgotPassword")]
        public async Task<IActionResult> ForgotPassword(ForgotPasswordCommand command)
        {
            if (!ModelState.IsValid)
            {
                return View(command);
            }

            var result = await _accountApplication.ForgotPassword(command);
            switch (result.Item1.Status)
            {
                case OperationResultStatus.Error:
                    ErrorAlert(result.Item1.Message);
                    break;
                case OperationResultStatus.Success:
                    var emailBody = _viewRenderService.RenderToStringAsync("_ResetPasswordEmail", result.Item2);
                    SendEmail.Send(result.Item2.Email, "بازیابی رمز عبور", emailBody);
                    SuccessAlert(result.Item1.Message);
                    return RedirectToAction("Index", "Home");
                case OperationResultStatus.NotFound:
                    ErrorAlert(result.Item1.Message);
                    break;
                default:
                    return NotFound();
            }

            return View(command);
        }

        #endregion

        #region Reset Password

        [Route("ResetPassword/{code}")]
        public async Task<IActionResult> ResetPassword(string code)
        {
            if (string.IsNullOrEmpty(code) || !await _accountApplication.CheckAccountByActiveCode(code))
            {
                return NotFound();
            }

            return View(new ResetPasswordCommand()
            {
                ActiveCode = code
            });
        }

        [HttpPost("ResetPassword/{code}")]
        public async Task<IActionResult> ResetPassword(ResetPasswordCommand command, string code)
        {
            if (!ModelState.IsValid)
            {
                return View(command);
            }

            var result = await _accountApplication.ResetPassword(command);

            switch (result.Status)
            {
                case OperationResultStatus.Error:
                    ErrorAlert(result.Message);
                    break;
                case OperationResultStatus.Success:
                    SuccessAlert(result.Message);
                    return RedirectToAction("Index", "Home");
                case OperationResultStatus.NotFound:
                    ErrorAlert(result.Message);
                    break;
                default:
                    return NotFound();
            }

            return View(command);
        }

        #endregion
    }
}

TopLearn/TopLearn.Web/Areas/Administrator/Pages/AccountManagement/Accounts/Create.cshtml
@using AccountManagement.Domain.RoleAgg
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model AccountManagement.Application.Contracts.Account.CreateAccountCommand
@{
    Layout = null;
}


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">افزودن حساب جدید</h4>
</div>

<form asp-page="Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="FullName" class="control-label">نام</label>
                    <input class="form-control" asp-for="FullName" />
                    <span asp-validation-for="FullName" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Username" class="control-label">نام کاربری</label>
                    <input class="form-control" asp-for="Username">
                    <span asp-validation-for="Username" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Profile" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="Profile" accept="image/*">
                    <span asp-validation-for="Profile" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Email" class="control-label">ایمیل</label>
                    <input class="form-control" asp-for="Email">
                    <span asp-validation-for="Email" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-9">
                <div class="form-group">
                    <label asp-for="Password" class="control-label">کلمه عبور</label>
                    <input class="form-control" asp-for="Password">
                    <span asp-validation-for="Password" class="error"></span>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label asp-for="IsActive" class="control-label">فعال بودن حساب</label>
                    <input class="form-control" asp-for="IsActive">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    @foreach (var item in Model.Roles)
                    {
                        <div>
                            <input type="checkbox" name="selectedRoles" id="selectedRoles" value="@item.Id"
                            @(item.Id == RolesCode.User ? "checked" : "")>
                            <label>
                                @item.RoleTitle
                            </label>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-success waves-effect waves-light">ایجاد</button>
    </div>
</form>

TopLearn/TopLearn.Web/Areas/Administrator/Pages/AccountManagement/Accounts/Edit.cshtml
@model AccountManagement.Application.Contracts.Account.EditAccountCommand
@using Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = null;
}


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش حساب</h4>
</div>

<form asp-page="Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <input type="hidden" asp-for="Id" value="@Model.Id" />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="FullName" class="control-label">نام</label>
                    <input class="form-control" asp-for="FullName" />
                    <span asp-validation-for="FullName" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Username" class="control-label">نام کاربری</label>
                    <input class="form-control" asp-for="Username">
                    <span asp-validation-for="Username" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Profile" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="Profile" accept="image/*">
                    <span asp-validation-for="Profile" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Email" class="control-label">ایمیل</label>
                    <input class="form-control" asp-for="Email">
                    <span asp-validation-for="Email" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    @foreach (var item in Model.Roles)
                    {
                        <div>
                            <input type="checkbox" name="selectedRoles" id="selectedRoles" value="@item.Id"
                            @(Model.AccountRoles.Contains(item.Id) ? "checked" : "")>
                            <label>
                                @item.RoleTitle
                            </label>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-success waves-effect waves-light">ذخیره تغییرات</button>
    </div>
</form>

TopLearn/TopLearn.Web/Areas/Administrator/Pages/AccountManagement/Accounts/Index.cshtml
@page
@model TopLearn.Web.Areas.Administrator.Pages.AccountManagement.Accounts.IndexModel
@{
    ViewData["Title"] = "کاربران";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("Index", "Create")">افزودن کاربر جدید</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در کابران</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Email"></label>
                        <input class="form-control" asp-for="SearchModel.Email" placeholder="ایمیل">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.FullName"></label>
                        <input class="form-control" asp-for="SearchModel.FullName" placeholder="نام کاربر">
                    </div>
                    <div class="form-group m-r-10">
                        <div class="checkbox checkbox-primary">
                            <input asp-for="SearchModel.NotActivatedAccount">
                            <label asp-for="SearchModel.NotActivatedAccount">
                                حساب های غیرفعال
                            </label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" href="/Administrator/AccountManagement/Accounts/Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست حساب ها</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>نام</th>
                                    <th>تصویر</th>
                                    <th>ایمیل</th>
                                    <th>نام کاربری</th>
                                    <th>وضعیت حساب</th>
                                    <th>تاریخ ثبت</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model.Accounts)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.FullName</td>
                                        <td>
                                            <img src="~/Files/UserImages/@item.ImageName" alt="User Image" title="@item.FullName" width="80px" />
                                        </td>
                                        <td>@item.Email</td>
                                        <td>@item.Username</td>
                                        @if (item.IsActive)
                                        {
                                            <td class="text-success">فعال</td>
                                        }
                                        else
                                        {
                                            <td class="text-danger">غیرفعال</td>
                                        }
                                        <td>@item.RegisterDate</td>
                                        <td>
                                            <a class="btn btn-warning btn-xs" href="#showmodal=@Url.Page("Index", "Edit", new { id = item.Id })">
                                                <i class="fa fa-edit"></i>ویرایش
                                            </a>
                                            <a class="btn btn-primary btn-xs" href="">
                                                <i class="fa fa-key"></i>تغییر رمز
                                            </a>
                                            @if (item.IsActive)
                                            {
                                                <a class="btn btn-danger btn-xs" asp-page="Index" asp-page-handler="DeActiveAccount" asp-route-id="@item.Id">
                                                    <i class="fa fa-remove"></i>غیرفعال کردن
                                                </a>
                                            }
                                            else
                                            {
                                                <a class="btn btn-success btn-xs" asp-page="Index" asp-page-handler="ActiveAccount" asp-route-id="@item.Id">
                                                    <i class="fa fa-check"></i>فعال کردن
                                                </a>
                                            }
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/admin/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/admin/assets/datatables/dataTables.bootstrap.js"></script>


    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}