TopLearn/TopLearn.Web/Areas/UserPanel/Controllers/WalletController.cs
using _0.Framework.Application;
using AccountManagement.Application.Contracts.Wallet;
using AccountManagement.Common.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TopLearn.Web.Controllers;

namespace TopLearn.Web.Areas.UserPanel.Controllers
{
    [Area("UserPanel")]
    [Authorize]
    public class WalletController : BaseController
    {
        #region constructor injection

        private readonly IWalletApplication _walletApplication;
        private readonly IAuthenticationHelper _authenticationHelper;
        public WalletController(IWalletApplication walletApplication, IAuthenticationHelper authenticationHelper)
        {
            _walletApplication = walletApplication;
            _authenticationHelper = authenticationHelper;
        }

        #endregion

        [Route("UserPanel/Wallet")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost("UserPanel/Wallet")]
        public async Task<IActionResult> Index(ChargeWalletCommand command)
        {
            if (!ModelState.IsValid)
            {
                return View(command);
            }

            command.AccountId = _authenticationHelper.CurrentAccountId();
            command.IsPayed = false;

            var result = await _walletApplication.ChargeWallet(command);
            switch (result.Item1.Status)
            {
                case OperationResultStatus.Error:
                    ErrorAlert(result.Item1.Message);
                    return View(command);
                case OperationResultStatus.Success:
                    break;
                case OperationResultStatus.NotFound:
                    ErrorAlert(result.Item1.Message);
                    return View(command);
                default:
                    return NotFound();
            }

            #region Online Payment

            var amount = Convert.ToInt32(command.Amount);
            var email = _authenticationHelper.CurrentAccountEmail();
            var payment = new ZarinpalSandbox.Payment(amount);
            var callBackUrl = $"https://localhost:7135/CallBack?walletId={result.Item2}";

            var response = await payment.PaymentRequest("شارژ کیف پول",
                callBackUrl, email, "");

            if (response.Status == 100)
            {
               return Redirect("https://sandbox.zarinpal.com/pg/StartPay/" + response.Authority);
            }

            #endregion

            return BadRequest();
        }
    }
}

TopLearn/TopLearn.Web/Areas/UserPanel/ViewComponents/UserPanelSidebarViewComponent.cs
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Common.Authentication;
using Microsoft.AspNetCore.Mvc;

namespace TopLearn.Web.Areas.UserPanel.ViewComponents;

public class UserPanelSidebarViewComponent : ViewComponent
{
    #region constructor injection

    private readonly IAccountApplication _accountApplication;
    private readonly IAuthenticationHelper _authenticationHelper;
    public UserPanelSidebarViewComponent(IAccountApplication accountApplication, IAuthenticationHelper authenticationHelper)
    {
        _accountApplication = accountApplication;
        _authenticationHelper = authenticationHelper;
    }

    #endregion
    public async Task<IViewComponentResult> InvokeAsync()
    {
        var email = _authenticationHelper.CurrentAccountEmail();
        var account = await _accountApplication.UserPanelSidebar(email);
        return View("~/Areas/UserPanel/Views/Shared/Components/UserPanelSidebar.cshtml", account);
    }
}

TopLearn/TopLearn.Web/Areas/UserPanel/ViewComponents/WalletReportViewComponent.cs
using AccountManagement.Application.Contracts.Wallet;
using AccountManagement.Common.Authentication;
using Microsoft.AspNetCore.Mvc;

namespace TopLearn.Web.Areas.UserPanel.ViewComponents;

public class WalletReportViewComponent: ViewComponent
{

    #region constructor injection

    private readonly IWalletApplication _walletApplication;
    private readonly IAuthenticationHelper _authenticationHelper;
    public WalletReportViewComponent(IWalletApplication walletApplication, IAuthenticationHelper authenticationHelper)
    {
        _walletApplication = walletApplication;
        _authenticationHelper = authenticationHelper;
    }

    #endregion

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var accountId = _authenticationHelper.CurrentAccountId();
        var wallets = await _walletApplication.WalletReports(accountId);
        return View("~/Areas/UserPanel/Views/Shared/Components/WalletReport.cshtml", wallets);
    }
}

TopLearn/TopLearn.Web/Areas/UserPanel/Views/Wallet/Index.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model AccountManagement.Application.Contracts.Wallet.ChargeWalletCommand
@{
    ViewData["Title"] = "کیف پول شما";
}

<div class="container">
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a asp-area="" asp-controller="Home" asp-action="Index">تاپ لرن</a></li>
            <li class="breadcrumb-item"><a asp-area="UserPanel" asp-controller="Home" asp-action="Index">حساب کاربری</a></li>
            <li class="breadcrumb-item active" aria-current="page"> کیف پول شما </li>
        </ul>
    </nav>
</div>

<main>
    <div class="container">
        <div class="user-account">
            <div class="row">
                @* Sidebar *@
                @await Component.InvokeAsync("UserPanelSidebar")

                <div class="col-md-9 col-sm-8 col-xs-12">
                    <section class="user-account-content">
                        <header>
                            <h1> گزارش کیف شما </h1>
                        </header>
                        <div class="inner">
                            <h3> شارژ کیف پول </h3>
                            <div class="inner form-layer">
                                <form asp-area="UserPanel" asp-controller="Wallet" asp-action="Index"
                                      method="post">
                                    <div class="row">
                                        <div class="col-md-7 col-sm-8 col-xs-12">
                                            <div class="input-group">
                                                <span class="input-group-addon"><i class="zmdi zmdi-money"></i></span>
                                                <input type="number" asp-for="Amount" class="form-control" placeholder="مبلغ به تومان">
                                            </div>
                                        </div>
                                        <div asp-validation-summary="All" class="text-danger"></div>
                                        <div class="col-md-7 col-sm-8 col-xs-12">
                                            <button class="btn btn-success"> شارژ کیف پول </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <hr />
                            @await Component.InvokeAsync("WalletReport")
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</main>

@section Scripts
    {
    <partial name="_ValidationScriptsPartial" />
}